use_frameworks!

platform :ios, '8.0'

target 'LWWordConverter_Example' do
  pod 'LWWordConverter', :path => '../'

  pod 'SQLCipher'
  pod 'AFNetworking'

  # target 'LWWordConverter_Tests' do
  #   inherit! :search_paths
  # end
end
